import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from "@/Components/Footer";
import Header from "@/Components/Header";
import LeftAside from "@/Components/LeftAside";
import RightAside from "@/Components/RightAside";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Header />
        <main className="row">
          <LeftAside />
          {children}

          <RightAside />
        </main>
        <Footer />

      </body>
    </html>
  )
}
